#!/usr/bin/env python3
"""Generate sources/config-instances.yaml for the gftools builder.

The config declares one static instance for each point of the grid:
Roman/Italic x opsz(8-144) x wdth(25-151) x wght(100-1000). The builder
cuts each instance from the variable fonts with gftools-gen-static,
which writes GF-spec name tables (non-wght particles join the family
name, see https://googlefonts.github.io/gf-guide/statics.html).

gen-static cannot set everything, so the recipe section appends
gftools-fontsetter steps that use the files in sources/static-fixes/:
  - Italic statics get post.italicAngle = -12 (the drawing is slanted
    at slnt=0).
  - Non-default widths get the correct OS/2.usWidthClass.
  - wght=1000 ("ExtraBlack", not a registered fallback) gets
    OS/2.usWeightClass = 1000.

Particle names come from the GF Axis Registry fallbacks, with two
overrides that the registry does not cover: wdth 151 = "ExtraExpanded"
(Roboto Flex precedent) and wght 1000 = "ExtraBlack".

This script replaces the old build-RobotoDelta-statics.sh. To change
the grid, edit this file and run:

    python3 tools/gen_statics_config.py
"""

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(REPO, "sources", "config-instances.yaml")

POSTURES = ["Roman", "Italic"]
OPTICAL_SIZES = [8, 14, 36, 72, 144]
WIDTHS = [25, 50, 75, 100, 125, 151]
WEIGHTS = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

# GF Axis Registry fallback names. Defaults (opsz 14, wdth 100) are
# elided from the family name.
OPSZ_NAMES = {8: "8pt", 14: None, 36: "36pt", 72: "72pt", 144: "144pt"}
WDTH_NAMES = {
    25: "SuperCondensed",
    50: "UltraCondensed",
    75: "Condensed",
    100: None,
    125: "Expanded",
    151: "ExtraExpanded",
}
WGHT_NAMES = {
    100: "Thin",
    200: "ExtraLight",
    300: "Light",
    400: "Regular",
    500: "Medium",
    600: "SemiBold",
    700: "Bold",
    800: "ExtraBold",
    900: "Black",
    1000: "ExtraBlack",
}

# OS/2.usWidthClass for each non-default width.
WIDTH_CLASS_FIX = {25: "width-25", 50: "width-50", 75: "width-75",
                   125: "width-125", 151: "width-151"}

HEADER = """\
# Generated by tools/gen_statics_config.py -- do not edit by hand.
# Edit the generator and re-run it instead.
recipeProvider: googlefonts
sources:
  - ./Roman/RobotoDelta.designspace
  - ./Italic/RobotoDelta-Italic.designspace
checkCompatibility: False
familyName: "Roboto Delta"
splitItalic: false
buildWebfont: false
autohintTTF: false
"""


def family_name(opsz, wdth):
    particles = [OPSZ_NAMES[opsz], WDTH_NAMES[wdth]]
    return " ".join(["Roboto Delta"] + [p for p in particles if p])


def style_name(wght, italic):
    style = WGHT_NAMES[wght]
    if italic:
        style = "Italic" if style == "Regular" else style + " Italic"
    return style


def main():
    instances = []
    fixes = []  # (target, [fontsetter yaml, ...])
    for posture in POSTURES:
        italic = posture == "Italic"
        for opsz in OPTICAL_SIZES:
            for wdth in WIDTHS:
                for wght in WEIGHTS:
                    out = (
                        f"fonts/statics/{posture}-opsz{opsz}-wdth{wdth}/"
                        f"RobotoDelta-{posture}-opsz{opsz}-wdth{wdth}-wght{wght}.ttf"
                    )
                    instances.append(
                        f"  - familyName: {family_name(opsz, wdth)}\n"
                        f"    styleName: {style_name(wght, italic)}\n"
                        f"    out: {out}\n"
                        f"    coordinates:\n"
                        f"      opsz: {opsz}\n"
                        f"      wdth: {wdth}\n"
                        f"      wght: {wght}\n"
                    )
                    steps = []
                    if italic:
                        steps.append("italic")
                    if wdth in WIDTH_CLASS_FIX:
                        steps.append(WIDTH_CLASS_FIX[wdth])
                    if wght == 1000:
                        steps.append("weight-1000")
                    if steps:
                        fixes.append((out, steps))

    with open(CONFIG, "w") as fp:
        fp.write(HEADER)
        fp.write("instances:\n")
        fp.writelines(instances)
        fp.write("recipe:\n")
        for out, steps in fixes:
            fp.write(f'  "../{out}":\n')
            for step in steps:
                fp.write(f"    - postprocess: fontsetter\n")
                fp.write(f"      args: static-fixes/{step}.yaml\n")

    print(f"Wrote {CONFIG}: {len(instances)} instances, "
          f"{len(fixes)} postprocess targets")


if __name__ == "__main__":
    main()
